# Development docker-compose override
# Use: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  web:
    build:
      target: builder  # Use builder stage for development
    volumes:
      - .:/app
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    environment:
      - ENVIRONMENT=development